---

- name: apt-cacher-ng present
  apt:
    name: ["apt-cacher-ng", "avahi-daemon", "auto-apt-proxy"]
    state: present


- name: Creates data directory
  file:
    path: "{{ aptcacher_dir_data }}"
    state: directory
    owner: apt-cacher-ng
    group: apt-cacher-ng
    mode: 0755
    recurse: True

- name: copy mirror files
  copy:
    dest: "{{aptcacher_dir_cnf}}"
    src:  "{{ item }}"
  loop: "{{ aptCacher_mirrorfiles }}" 
    
- name: Configurasion template 
  template:
    src:  acng.conf.j2
    dest:  "{{ aptcacher_dir_cnf }}/acng.conf" 
    mode:  0644
    owner:  root
    group:  root 
  notify:
   - restart apt-cacher-ng

- name: ensure apt-cacher-ng is running
  service:
    name: apt-cacher-ng
    state: started
